apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: genaistarterstackacr.azurecr.io/chatbot:latest
        ports:
        - containerPort: 80
        env:
        - name: OPENAI_API_KEY
          value: # Replace with your actual key
        - name: OPENAI_ENDPOINT
          value: "https://genaistack-openai.openai.azure.com/" # Replace with your actual endpoint
        - name: QDRANT_HOST
          value: "qdrant"
        - name: QDRANT_PORT
          value: "6333" # Ensure this is a string "6333" for the environment variable
      imagePullSecrets:
      - name: acr-secret