apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "${resource_group_name}-kv" # Replace with your Key Vault name
    tenantId: "${tenant_id}" # Replace with your Azure Tenant ID
    objects: |
      array:
        - | 
          objectName: openai-api-key
          objectType: secret
          objectVersion: ""
        - | 
          objectName: openai-endpoint
          objectType: secret
          objectVersion: ""